### ISSUE TITLE
Shoutouts returning the user that types it?

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#20]
Hello,

So I've been tinkering with this as you can see below, However i seem to be having an issue, I may just be missing something... But just checking to see if I'm making a simple mistake?

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/c9c1b494-66b2-4ea4-ae4b-62f00ff15770)

I am Typing in the following but the outcome is always my name?

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/085428b8-c890-445a-9f54-3ed711127ecb)

But Im getting the following instead of it showing SendMemesPlox its showing my name? I've used %targetUser% I've tried %targetUserName% and it still returns value of my name or whoever types it.

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/78150e29-dd42-4a16-9afb-16568278f528)

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/1c88d1cc-3ce7-4b53-95f1-3af45bb3cf8b)

**Comment by Jyojibh** [comment]
So as you can see here I've got it set to Trigger the sounds I have, However It doesnt take it from the cooldowns I have set.

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/c3d1e146-bf6c-430b-81ab-96ec586477fc)

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/6c897e38-f1c2-4cbb-9a82-5112423ed3a6)

**Comment by Sehelitar** [comment]
Cooldowns triggers are also known as "command is denied because it is in cooldown" triggers.
Usually these are used to send a message back to the user issuing the command like "This command is in cooldown. Try again later." so they know what is going on.

You should just use the "normal" commands triggers for your actions. These triggers wont be called if a cooldown is in effect, but the cooldowns ones will.

**Comment by Jyojibh** [comment]
I see where I went wrong, I forgot to remove the twitch commands where it should have been the Kick! Such a simple mistake! Thanks again!
