### ISSUE TITLE
[Request]fetch user who unfollows

### ISSUE THREAD

**Issue by mocchimon** [Sehelitar/Kick.bot#26]
another bot called kicklet had this feature but was removed today. having this option would be cool

**Comment by Sehelitar** [comment]
Hi!
AFAIK, the reason Kicklet removed this feature is basically the same reason I didn't implement it in Kick.bot in the first place : this kind of information cannot do any good to anyone. They removed it because people were using it for very bad reasons (intimidation, bullying, etc...)
Is there any *good* reason to have this? To track your follow count maybe? (which could be linked to #24)
