### ISSUE TITLE
Plugin Stopped working

### ISSUE THREAD

**Issue by eGirlsStream** [Sehelitar/Kick.bot#63]
Kick did some sort of update and the plugin stopped working properly last night. The triggers do not show up and methods do nothing. I think they invalidated the API key or something.

**Comment by Sehelitar** [comment]
Yes, Kick made a breaking change a few hours ago without prior notice.
This update should fix that : https://github.com/Sehelitar/Kick.bot/releases/tag/v0.4.1

**Comment by peecee-uk** [comment]
Hi.
Luckily found the update after Kick's update. Thanks!
Cannot seem to get botrix sub test to trigger anything configured in streamerbot.
Created a separate streamerbot instance from my regular one just to isolate the Kick integration.
Set up from fresh, compiled using new dll files, authenticated into Kick when prompted, added a trigger action which works using the test trigger function in streamerbot but it seems as though external triggers, like the tests from Botrix for subs etc etc are not hitting streamerbot.

Any thoughts or other tests you might be able to recommend??

**Comment by Sehelitar** [comment]
Botrix testing features are limited to Botrix itself, the same way that Streamer.bot test triggers won't affect Botrix either. These fake triggers are just supposed to test your actions within the app itself, they don't exist so they cannot reach external actors or Kick itself since Kick is the only "trusted" source and events only go one way.

The only way to properly test your actions within Streamer.bot is to use the "Test" trigger (the trigger is in "Core" => "Test"). Set the arguments your action requires to test it (see the wiki documentation for expected values) and fire it up!

**Comment by peecee-uk** [comment]
Hi,

Had a feeling that was going to be the case based on what I am seeing.
Thanks for the quick response and also for putting this together. 
Much appreciated!
